
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lee_934859
 */
public class MainWindow extends javax.swing.JFrame {
    private TreeMap<Integer, Team> teams;
    private TreeSet<Integer> rankedTeams;
    private TreeSet<QualsMatch> matches;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panel_teams = new javax.swing.JPanel();
        scrollPane_teams = new javax.swing.JScrollPane();
        table_teams = new javax.swing.JTable();
        comboBox_displayStat = new javax.swing.JComboBox();
        panel_matches = new javax.swing.JPanel();
        panel_scouting = new javax.swing.JPanel();
        panel_simulations = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_team = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_teams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team", "Name", "RP", "OPR", "DPR", "Matches", "(Display Stat)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_teams.setViewportView(table_teams);

        comboBox_displayStat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox_displayStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_displayStatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_teamsLayout = new javax.swing.GroupLayout(panel_teams);
        panel_teams.setLayout(panel_teamsLayout);
        panel_teamsLayout.setHorizontalGroup(
            panel_teamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_teamsLayout.createSequentialGroup()
                .addContainerGap(736, Short.MAX_VALUE)
                .addComponent(comboBox_displayStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(scrollPane_teams)
        );
        panel_teamsLayout.setVerticalGroup(
            panel_teamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_teamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBox_displayStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane_teams, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Teams", panel_teams);

        javax.swing.GroupLayout panel_matchesLayout = new javax.swing.GroupLayout(panel_matches);
        panel_matches.setLayout(panel_matchesLayout);
        panel_matchesLayout.setHorizontalGroup(
            panel_matchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        panel_matchesLayout.setVerticalGroup(
            panel_matchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Matches", panel_matches);

        javax.swing.GroupLayout panel_scoutingLayout = new javax.swing.GroupLayout(panel_scouting);
        panel_scouting.setLayout(panel_scoutingLayout);
        panel_scoutingLayout.setHorizontalGroup(
            panel_scoutingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        panel_scoutingLayout.setVerticalGroup(
            panel_scoutingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Scouting", panel_scouting);

        javax.swing.GroupLayout panel_simulationsLayout = new javax.swing.GroupLayout(panel_simulations);
        panel_simulations.setLayout(panel_simulationsLayout);
        panel_simulationsLayout.setHorizontalGroup(
            panel_simulationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        panel_simulationsLayout.setVerticalGroup(
            panel_simulationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Simulations", panel_simulations);

        menu_file.setText("File");
        menuBar.add(menu_file);

        menu_team.setText("Team");
        menuBar.add(menu_team);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBox_displayStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_displayStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_displayStatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox_displayStat;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_team;
    private javax.swing.JPanel panel_matches;
    private javax.swing.JPanel panel_scouting;
    private javax.swing.JPanel panel_simulations;
    private javax.swing.JPanel panel_teams;
    private javax.swing.JScrollPane scrollPane_teams;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable table_teams;
    // End of variables declaration//GEN-END:variables
}
